% Wire Model
% Mohammad Shahrad
function [elmore_delay] = wire_model_2(N)
%N   =   100;            % Number of chain elements 
edges = 15;

Len =   1000;           % Length of wire in micro-meters
Wid =   0.12;           % Width in micro-meters
Rs  =   0.065;          % Resistance per micro-meters sqaure
Cpps=   30e-18;         % Parallel plate capacitance per micro-meters square
Cfl =   40e-18;         % Fringing capacitance per micro-meter
Ll  =   0;
Rw  =   Len*Rs/Wid;     % Wire resistance
Cppw=   Len*Wid*Cpps;   % Wire parallel plate capacitance
Cfw =   2*Len*Cfl;      % Wire fringing capacitance
Lw  =   Len*Ll;
C_ld=   0;              % Load capacitor at wire destination

mu_w =  1;              % Average width for the Normal distribution function
sig_w =  0.1;           % Sigma for the Normal distrubution function of width
mu_h =  1;              % Average height for the Normal distribution function
sig_h =  0.1;           % Sigma for the Normal distrubution function of height

pd_w =  makedist('Normal','mu',mu_w,'sigma',sig_w);     % Normal DF for width
fac_w =  random(pd_w,[1,N]);                            % Random Chain Factors for width
pd_h =  makedist('Normal','mu',mu_h,'sigma',sig_h);     % Normal DF for width
fac_h =  random(pd_h,[1,N]);                            % Random Chain Factors for width

R   =   ( ( (Rw/N)*ones(1,N) ) ./ (fac_w) ) ./ (fac_h); % Resistor per chain element
Cpp =   ( (Cppw/N)*ones(1,N) ) .* (fac_w);              % Parallel plate apacitor per chain element
Cf  =   ( (Cfw/N)*ones(1,N) ) .* (fac_h);               % Parallel plate apacitor per chain element
C   =   Cpp + Cf;
L   =   Lw/N*ones(1,N);

% Generating the SPICE Netlist
dlmwrite('wire_model_1.sp','* Code generated by MATLAB','-append');
dlmwrite('wire_model_1.sp','.param vdd=1.2V','-append');
% R
for j=1:N
    str = sprintf('R%d %d %d %d',j,2*j-1,2*j,R(j));
    dlmwrite('wire_model_1.sp',str,'-append');
end
% L
for j=1:N
    str = sprintf('L%d %d %d %d',j,2*j,2*j+1,L(j));
    dlmwrite('wire_model_1.sp',str,'-append');
end
% C
str = sprintf('C0 1 0 %d',C(N)/2);
dlmwrite('wire_model_1.sp',str,'-append');
for j=1:N-1
    str = sprintf('C%d %d 0 %d',j,2*j+1,C(j));
    dlmwrite('wire_model_1.sp',str,'-append');
end
% C_load
str = sprintf('C%d %d 0 %d',N,2*N+1,C(N)/2+C_ld);
dlmwrite('wire_model_1.sp',str,'-append');


str = sprintf('VSW 1 0 PULSE (0V vdd 5ns 1ns 1ns 5ns 10ns)');
dlmwrite('wire_model_1.sp',str,'-append');
for j=1:edges
    str = sprintf('.meas tran tp_hl%d TRIG v(1) VAL=''vdd/2'' FALL=%d TARG v(%d) VAL=''vdd/2'' FALL=%d',j,j+1,2*N+1,j+1);
    dlmwrite('wire_model_1.sp',str,'-append');
end
for j=1:edges
    str = sprintf('.meas tran tp_lh%d TRIG v(1) VAL=''vdd/2'' RISE=%d TARG v(%d) VAL=''vdd/2'' RISE=%d',j,j+1,2*N+1,j+1);
    dlmwrite('wire_model_1.sp',str,'-append');
end

dlmwrite('wire_model_1.sp','.options nomod post','-append');
dlmwrite('wire_model_1.sp','.tran 10fs 400ns','-append');
dlmwrite('wire_model_1.sp','.END wire_model_1','-append');

% v   =   zeros(N+1,1);
% 
% syms s t
% 
% 
% i   =   zeros(N+1,1);
% i(N+1)= C_ld*s*v(N+1);
% for j=N:-1:1
%     v(j) = v(j+1) + ( C(j)*s*v(j+1) + i(j+1) ) * ( R(j) + L(j)*s );
% end

%plot(R)
%hold on
%plot(C)

elmore_delay = log(2)*(N+1)*Rw*(Cppw + Cfw)/(2*N)


